#!/bin/bash

# Initializes a freshly created npm module to compile CoffeeScript files using broccoli.
# See https://github.com/RedNifre/kitchen-sink

src="src"
lib="lib"

if [ $# -gt 0 ]
	then
		src=$1
fi

if [ $# = 2 ]
	then
		lib=$2
fi


mkdir $src



npm install --save-dev broccoli
npm install --save-dev broccoli-coffee



echo "
# compiled javascript
$lib/

# broccoli-timepiece temp directory
tmp/

# dependencies
node_modules
" >> .gitignore



echo "
$src/
tmp/
" >> .npmignore



echo "#!/bin/bash
broccoli-timepiece $lib/" > broc.sh



chmod +x broc.sh



echo "module.exports = require('broccoli-coffee')('$src',{bare:true})" >> Brocfile.js
